mmitv_back_bundle_user_user:
    resource: "@MmitvBackBundleUserBundle/Resources/config/routing/user.yml"
    prefix:   /back/utilisateurs/

mmitv_back_bundle_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MmitvBackBundleUserBundle:Default:index }
