mmitv_back_bundle_user:
    resource: "@MmitvBackBundleUserBundle/Resources/config/routing.yml"
    prefix:   /

mmitv_back:
    resource: "@MmitvBackBundle/Resources/config/routing.yml"
    prefix:   /

mmitv_front:
    resource: "@MmitvFrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

