mmitv_front_homepage:
    path:     /hello/{name}
    defaults: { _controller: MmitvFrontBundle:Default:index }


mmitv_front_index:
    path:     /
    defaults: { _controller: MmitvFrontBundle:Front:index }

mmitv_front_json:
    path:     /index/json
    defaults: { _controller: MmitvFrontBundle:Front:json, _format: json }
