mmitv_back_homepage:
    path:     /hello/{name}
    defaults: { _controller: MmitvBackBundle:Default:index }

mmitv_back_index:
    path:     /back/index
    defaults: { _controller: MmitvBackBundle:Index:index }

mmitv_back_video_index:
    path:     /back/video/index
    defaults: { _controller: MmitvBackBundle:Video:index }

mmitv_back_planning_index:
    path:     /back/planning/index
    defaults: { _controller: MmitvBackBundle:Planning:index }

mmitv_back_twitter_index:
    path:     /back/twitter/index
    defaults: { _controller: MmitvBackBundle:Twitter:index }

mmitv_back_twitter_add:
    path:     /back/twitter/add
    defaults: { _controller: MmitvBackBundle:Twitter:add }

mmitv_back_utilisateurs_index:
    path:     /back/utilisateurs/index
    defaults: { _controller: MmitvBackBundle:Utilisateurs:index }

mmitv_back_utilisateurs_add:
    path:     /back/utilisateurs/add
    defaults: { _controller: MmitvBackBundle:Utilisateurs:add }
