mmitv_back_homepage:
    path:     /hello/{name}
    defaults: { _controller: MmitvBackBundle:Default:index }

mmitv_back_index:
    path:     /back/index
    defaults: { _controller: MmitvBackBundle:Index:index }

mmitv_back_video_index:
    path:     /back/video/index
    defaults: { _controller: MmitvBackBundle:Video:index }

mmitv_back_video_add:
    path:     /back/video/add
    defaults: { _controller: MmitvBackBundle:Video:add }

mmitv_back_video_edit:
    path:     /back/video/edit/{id}
    defaults: { _controller: MmitvBackBundle:Video:edit }

mmitv_back_video_delete:
    path:     /back/video/delete/{id}
    defaults: { _controller: MmitvBackBundle:Video:delete }

mmitv_back_planning_index:
    path:     /back/planning/index
    defaults: { _controller: MmitvBackBundle:Planning:index }

mmitv_back_twitter_index:
    path:     /back/twitter/index
    defaults: { _controller: MmitvBackBundle:Twitter:index }

mmitv_back_twitter_edit:
    path:     /back/twitter/edit/{id}
    defaults: { _controller: MmitvBackBundle:Twitter:edit }

mmitv_back_twitter_delete:
    path:     /back/twitter/delete/{id}
    defaults: { _controller: MmitvBackBundle:Twitter:delete }

mmitv_back_utilisateurs_index:
    path:     /back/utilisateurs/index
    defaults: { _controller: MmitvBackBundle:Utilisateurs:index }

mmitv_back_utilisateurs_add:
    path:     /back/utilisateurs/add
    defaults: { _controller: FOSUserBundle:Registration:register }

mmitv_back_utilisateurs_edit:
    path:     /back/utilisateurs/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

mmitv_back_onair_index:
    path:     /back/onair/index
    defaults: { _controller: MmitvBackBundle:Onair:index }

mmitv_back_onair_add:
    path:     /back/onair/add
    defaults: { _controller: MmitvBackBundle:Onair:add }

mmitv_back_onair_delete:
    path:     /back/onair/delete/{id}
    defaults: { _controller: MmitvBackBundle:Onair:delete }

mmitv_back_offair_index:
    path:     /back/offair/index
    defaults: { _controller: MmitvBackBundle:Offair:index }

mmitv_back_offair_add:
    path:     /back/offair/add
    defaults: { _controller: MmitvBackBundle:Offair:add }

mmitv_back_offair_delete:
    path:     /back/offair/delete/{id}
    defaults: { _controller: MmitvBackBundle:Offair:delete }
