<?php

namespace Mmitv\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * membreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class membreRepository extends EntityRepository
{
}
