<?php

namespace Mmitv\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * off_airRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class off_airRepository extends EntityRepository
{
}
