<?php

namespace Mmitv\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * offairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offairRepository extends EntityRepository
{
}
