<?php

namespace Mmitv\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * on_airRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class on_airRepository extends EntityRepository
{
}
