<?php

namespace Mmitv\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * tweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tweetRepository extends EntityRepository
{
}
